config/routes.rb
AAAWebsite::Application.routes.draw do
  
root :to => 'aaa_core#index'
  
match "/events" => "aaa_core#events", via: :get
  
match '/shop' => 'aaa_core#shop', via: :get
  
match '/discussion' => 'aaa_core#discussion', via: :get
  

end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
    @title = "Home"
  end

  def events
	@title = "Events"
  end

  def shop
	@title = "Shop"
  end

  def discussion
	@title = "Forum"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 def title
	base_title = "Ashtead Allotments Asscoiation"
	if @title.nil?
		base_title
	else
		"#{@title} | #{base_title}"
	end	
  end	
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<h1>AaaCore#index</h1>
<p>Find me in app/views/aaa_core/index.html.erb</p>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/layouts/_header.html.erb
<header>
	<h1>Ashtead Alloments Accociation<h1>
	<h2>Healthy Eating and Exercise preserve Life's Balance<h2>
</header>	
	

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Events", events_path %></li>
		<li><%= link_to "Discussion", discussion_path %></li>
		<li><%= link_to "Shop", shop_path %></li>
	</ul>
</nav>	
								

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title><%= title %></title>
 	<%= stylesheet_link_tag "application" %>
	<%= csrf_meta_tags %>
</head>

<body>

	<%= render 'layouts/header'%>
	<%= render 'layouts/navigation'%>

	<%= yield %>
	
</body>
</html>